abbr -a -- gL 'git pull'
abbr -a -- gR 'git rebase'
abbr -a -- gRa 'git rebase --abort'
abbr -a -- gRc 'git rebase --continue'
abbr -a -- gRi 'git rebase --interactive'
abbr -a -- gRs 'git rebase --skip'
abbr -a -- gS 'git submodule'
abbr -a -- gSa 'git submodule add'
abbr -a -- gSu 'git submodule update --init --recursive'
abbr -a -- ga 'git add'
abbr -a -- gb 'git branch --vv'
abbr -a -- gbD 'git branch --D'
abbr -a -- gbc 'git checkout --b'
abbr -a -- gbd 'git branch --d'
abbr -a -- gc 'git commit --verbose'
abbr -a -- gca 'git commit --amend --verbose'
abbr -a -- gcf 'git commit --fixup'
abbr -a -- gcl 'git clone'
abbr -a -- gco 'git checkout'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gd 'git diff'
abbr -a -- gf 'git fetch --prune'
abbr -a -- gg 'git grep'
abbr -a -- ggi 'git grep --i'
abbr -a -- gm 'git merge'
abbr -a -- gp 'git push'
abbr -a -- gpd 'git push --delete origin'
abbr -a -- gpf 'git push --force-with-lease'
abbr -a -- gpr 'gh pr create'
abbr -a -- gpt 'git push --tags'
abbr -a -- grps 'git rev-parse --short HEAD'
abbr -a -- gs 'git stash'
abbr -a -- gsp 'git stash pop'
abbr -a -- gst 'git status'
abbr -a -- gwC 'git clean -ffdx'
abbr -a -- gwd 'git diff'
abbr -a -- l 'exa --l --git --group-directories-first'
abbr -a -- la 'exa --l --git --group-directories-first --a'
abbr -a -- ta 'tmux a --t common'
abbr -a -- dc 'docker compose'
